// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACn_x0Sg-IiMqN0Uoy_fHdCjmm3dA528c',
    appId: '1:750476604537:web:d35c746942c3d604ebd0a8',
    messagingSenderId: '750476604537',
    projectId: 'yumyum-e8291',
    authDomain: 'yumyum-e8291.firebaseapp.com',
    storageBucket: 'yumyum-e8291.appspot.com',
    measurementId: 'G-NFFZBN3YC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdAxxaLwqmL2P6Kb-tp-gJCydp5mkIGqs',
    appId: '1:750476604537:android:555a82b12ace5938ebd0a8',
    messagingSenderId: '750476604537',
    projectId: 'yumyum-e8291',
    storageBucket: 'yumyum-e8291.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDawP_E-i7zjdhYhDIeZlIa7jD_u_ubH_0',
    appId: '1:750476604537:ios:c33618baf80c7748ebd0a8',
    messagingSenderId: '750476604537',
    projectId: 'yumyum-e8291',
    storageBucket: 'yumyum-e8291.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDawP_E-i7zjdhYhDIeZlIa7jD_u_ubH_0',
    appId: '1:750476604537:ios:c33618baf80c7748ebd0a8',
    messagingSenderId: '750476604537',
    projectId: 'yumyum-e8291',
    storageBucket: 'yumyum-e8291.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACn_x0Sg-IiMqN0Uoy_fHdCjmm3dA528c',
    appId: '1:750476604537:web:9915e1ed2a483cf3ebd0a8',
    messagingSenderId: '750476604537',
    projectId: 'yumyum-e8291',
    authDomain: 'yumyum-e8291.firebaseapp.com',
    storageBucket: 'yumyum-e8291.appspot.com',
    measurementId: 'G-3JY43P7424',
  );
}
